[package]
name = "init"
edition = "2021"

[dependencies]
sdk = { git = "https://github.com/Hyle-org/hyle.git", branch = "main", package = "hyle-contract-sdk" }
client-sdk = { git = "https://github.com/Hyle-org/hyle.git", branch = "main", default-features = false, package = "hyle-client-sdk" }
hyle-hyllar = { git = "https://github.com/Hyle-org/hyle.git", branch = "main", features = [
  "client",
], default-features = false, package = "hyle-hyllar" }
hyle-hydentity = { git = "https://github.com/Hyle-org/hyle.git", branch = "main", features = [
  "client",
], package = "hyle-hydentity" }
hyle-net = { git = "https://github.com/Hyle-org/hyle.git", branch = "main", features = [
], package = "hyle-net" }

tokio = { version = "1", features = ["full"] }
anyhow = "1.0.93"
serde = { version = "1.0", features = ["derive"] }

tracing = "0.1.41"
tracing-subscriber = { version = "0.3.18", features = ["env-filter"] }
clap = "4.5.28"
reqwest = "0.12.15"
hyper = "1.6.0"
bytes = "1.10.1"
hyper-util = "0.1.11"
http-body-util = "0.1.3"
serde_json = "1.0.140"
