[package]
name = "init"
edition = "2021"

[dependencies]
sdk = { path = "/home/bertrand/workspace/hyle/crates/contract-sdk", package = "hyle-contract-sdk" }
client-sdk = { path = "/home/bertrand/workspace/hyle/crates/client-sdk", default-features = false, package = "hyle-client-sdk" }
hyle-smt-token = { path = "/home/bertrand/workspace/hyle/crates/contracts/smt-token", features = [
  "client",
], default-features = false, package = "hyle-smt-token" }
hyle-hydentity = { path = "/home/bertrand/workspace/hyle/crates/contracts/hydentity", features = [
  "client",
], package = "hyle-hydentity" }
hyle-net = { path = "/home/bertrand/workspace/hyle/crates/hyle-net", features = [
], package = "hyle-net" }

tokio = { version = "1", features = ["full"] }
anyhow = "1.0.93"
serde = { version = "1.0", features = ["derive"] }

tracing = "0.1.41"
tracing-subscriber = { version = "0.3.18", features = ["env-filter"] }
clap = "4.5.28"
